models:
  gpt4o:
    name: "gpt-4o"
    base_url: "https://az.gptplus5.com/v1"
  grok-beta:
    name: "grok-beta"
    base_url: "https://api.x.ai/v1"
  gpt4:
    name: "gpt-4"
    base_url: "https://az.gptplus5.com/v1"
  gpt4_turbo:
    name: "gpt-4-turbo"
    base_url: "https://az.gptplus5.com/v1"
  gpt4_turbo_preview:
    name: "gpt-4-turbo-preview"
    base_url: "https://az.gptplus5.com/v1"
  gpt4_0125_preview:
    name: "gpt-4-0125-preview"
    base_url: "https://az.gptplus5.com/v1"
  gpt4_0613:
    name: "gpt-4-0613"
    base_url: "https://az.gptplus5.com/v1"
  gpt4_32k:
    name: "gpt-4-32k"
    base_url: "https://az.gptplus5.com/v1"
  gpt4_32k_0613:
    name: "gpt-4-32k-0613"
    base_url: "https://az.gptplus5.com/v1"
  gpt35_turbo:
    name: "gpt-3.5-turbo"
    base_url: "https://az.gptplus5.com/v1"
  gpt35_turbo_0125:
    name: "gpt-3.5-turbo-0125"
    base_url: "https://az.gptplus5.com/v1"
  gpt35_turbo_1106:
    name: "gpt-3.5-turbo-1106"
    base_url: "https://az.gptplus5.com/v1"
  gpt35_turbo_16k:
    name: "gpt-3.5-turbo-16k"
    base_url: "https://az.gptplus5.com/v1"
  gpt35_turbo_instruct:
    name: "gpt-3.5-turbo-instruct"
    base_url: "https://az.gptplus5.com/v1"
  gpt4o_2024_0513:
    name: "gpt-4o-2024-05-13"
    base_url: "https://az.gptplus5.com/v1"
  gpt4o_2024_0806:
    name: "gpt-4o-2024-08-06"
    base_url: "https://az.gptplus5.com/v1"
  gpt4o_2024_1120:
    name: "gpt-4o-2024-11-20"
    base_url: "https://az.gptplus5.com/v1"
  gpt4o_mini:
    name: "gpt-4o-mini"
    base_url: "https://az.gptplus5.com/v1"
  gpt4o_mini_2024_0718:
    name: "gpt-4o-mini-2024-07-18"
    base_url: "https://az.gptplus5.com/v1"